logo: # add logo name
title: Augmented Reality & Architecture
description: > # this means to ignore newlines until "baseurl:"
 AR & Architecture is a passion project by Adam Tomkins, aiming to
 introduce Architects to the tools of Augmented Reality, to build 
 beautiful AR projects.
permalink: ':title/'
baseurl: "/AR-Architecture" # the subpath of your site, e.g. /blog
url: "https://adamrtomkins.github.io" # the base hostname & protocol for your site


# Banner settings
video: mountains.mp4 # add banner video. Add your video file to the folder video
banner-title: Augmented Reality & Architecture # add banner title
banner-desc: # add banner description

# Author settings
author-pic: me.png # your photo
author-name: Adam Tomkins# your name
about-author: A Research Software Engineer and Neuroinformatic Tool Developer from Sheffield, UK
email: a.tomkins@sheffield.ac.uk
phone: N/A
website: https://adamrtomkins.github.io

# Social link
twitter_url:   # add url link

# Paginate
paginate: 12
paginate_path: /page:num/

# Build settings
markdown: kramdown
plugins:
  - jekyll-paginate
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
